import { Link, useRouterState } from "@tanstack/react-router";
import { AlertTriangle, Bell, Car, CreditCard, FileText, Gauge, HelpCircle, LogOut, Menu, Settings, ShieldCheck, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Brand } from "./brand";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
const items=[["Overview","/dashboard",Gauge],["Vehicles","/dashboard/vehicles",Car],["Issues","/dashboard/issues",AlertTriangle],["Payments","/dashboard/payments",CreditCard],["Documents","/dashboard/documents",FileText],["Alerts","/dashboard/alerts",Bell],["AutoPay","/dashboard/autopay",ShieldCheck],["Settings","/dashboard/settings",Settings]] as const;
export function DashboardShell({title,description,children}:{title:string;description:string;children:ReactNode}){const [open,setOpen]=useState(false);const path=useRouterState({select:s=>s.location.pathname});async function logout(){await supabase.auth.signOut();window.location.href="/login"}return <div className="min-h-screen bg-dashboard"><aside className={`fixed inset-y-0 left-0 z-50 w-56 border-r border-border bg-background p-4 transition-transform lg:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><div className="flex h-10 items-center justify-between"><Brand/><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(false)}><X/></Button></div><nav className="mt-8 space-y-1">{items.map(([label,to,Icon])=><Link key={to} to={to} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm ${path===to?"bg-accent font-medium text-accent-foreground":"text-muted-foreground hover:bg-muted"}`}><Icon className="size-4"/>{label}</Link>)}</nav><div className="absolute bottom-5 left-4 right-4 space-y-1"><Link to="/support" className="flex items-center gap-3 px-3 py-2 text-sm text-muted-foreground"><HelpCircle className="size-4"/>Help</Link><button onClick={logout} className="flex w-full items-center gap-3 px-3 py-2 text-sm text-muted-foreground"><LogOut className="size-4"/>Log Out</button></div></aside><div className="lg:pl-56"><header className="grid min-h-16 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border bg-background px-5 lg:px-8"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></Button><div className="min-w-0"><h1 className="truncate text-lg font-semibold">{title}</h1><p className="truncate text-xs text-muted-foreground">{description}</p></div><Link to="/dashboard/alerts" className="relative rounded-md p-2 text-muted-foreground"><Bell className="size-4"/><span className="absolute right-1 top-1 size-1.5 rounded-full bg-brand-blue"/></Link></header><main className="mx-auto max-w-dashboard p-5 lg:p-8">{children}</main></div></div>}
export function Stat({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-md border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{note&&<p className="mt-1 text-[11px] text-muted-foreground">{note}</p>}</div>}
